# Generated by Django 2.2.5 on 2019-11-07 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='organization',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Institution/Organization'),
        ),
    ]
